name: Run Pytest on PR

on:
  pull_request:
    branches: [ "main" ]  # Specify the branches to protect

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest, add additional dependencies if needed

    - name: Add 'src' to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run pytest
      run: pytest  # Run your tests